services:
  app:
    build: .
    volumes:
      - .:/app
      - ./.ssh:/root/.ssh
    environment:
      NODE_ENV: production
    restart: always
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8880:80"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    stdin_open: true
    tty: true
